-- Migration: Create roadmaps table for Roadmap Generator Agent
-- Created: 2025-12-03
-- STEP 4 nel flusso sequenziale THEMIS

-- Ensure uuid support exists
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table to store generated roadmaps
CREATE TABLE IF NOT EXISTS public.roadmaps (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  
  -- Identifiers
  roadmap_id TEXT NOT NULL UNIQUE,
  tenant_id TEXT,
  company_id TEXT,
  
  -- Basic info
  roadmap_name TEXT NOT NULL,
  version TEXT DEFAULT '1.0',
  horizon_months INTEGER NOT NULL,
  
  -- Core content
  executive_summary TEXT,
  vision JSONB,
  current_state JSONB,
  
  -- Roadmap phases (array of phase objects)
  phases JSONB NOT NULL DEFAULT '[]'::jsonb,
  
  -- Strategic priorities
  strategic_priorities JSONB DEFAULT '[]'::jsonb,
  
  -- Quick wins
  quick_wins JSONB DEFAULT '[]'::jsonb,
  
  -- Budget and resources
  total_budget JSONB,
  resource_plan JSONB,
  
  -- Governance
  governance JSONB,
  
  -- Metrics and risks
  success_metrics JSONB DEFAULT '[]'::jsonb,
  overall_risks JSONB DEFAULT '[]'::jsonb,
  external_dependencies JSONB DEFAULT '[]'::jsonb,
  
  -- Recommendations
  recommendations JSONB DEFAULT '[]'::jsonb,
  
  -- Confidence and metadata
  confidence_level TEXT DEFAULT 'medium',
  assumptions JSONB DEFAULT '[]'::jsonb,
  notes TEXT,
  
  -- Full result JSON for reference
  result JSONB,
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_roadmaps_tenant_id ON public.roadmaps (tenant_id);
CREATE INDEX IF NOT EXISTS idx_roadmaps_company_id ON public.roadmaps (company_id);
CREATE INDEX IF NOT EXISTS idx_roadmaps_created_at ON public.roadmaps (created_at DESC);

-- Index for querying by horizon
CREATE INDEX IF NOT EXISTS idx_roadmaps_horizon ON public.roadmaps (horizon_months);

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION update_roadmaps_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_roadmaps_updated_at ON public.roadmaps;
CREATE TRIGGER trigger_roadmaps_updated_at
  BEFORE UPDATE ON public.roadmaps
  FOR EACH ROW
  EXECUTE FUNCTION update_roadmaps_updated_at();

-- Enable RLS (Row Level Security) if needed
ALTER TABLE public.roadmaps ENABLE ROW LEVEL SECURITY;

-- Policy to allow read/write based on tenant_id (adjust as needed)
CREATE POLICY roadmaps_tenant_policy ON public.roadmaps
  FOR ALL
  USING (tenant_id = current_setting('app.current_tenant', true) OR tenant_id IS NULL)
  WITH CHECK (tenant_id = current_setting('app.current_tenant', true) OR tenant_id IS NULL);

-- Grant permissions (adjust based on your setup)
GRANT ALL ON public.roadmaps TO authenticated;
GRANT ALL ON public.roadmaps TO service_role;

COMMENT ON TABLE public.roadmaps IS 'Stores strategic roadmaps generated by the Roadmap Generator Agent (Step 4)';
COMMENT ON COLUMN public.roadmaps.phases IS 'Array of roadmap phases with objectives, milestones, and resources';
COMMENT ON COLUMN public.roadmaps.strategic_priorities IS 'Prioritized list of strategic areas to address';
COMMENT ON COLUMN public.roadmaps.quick_wins IS 'Low-effort high-impact actions for immediate execution';
