-- Migration 021: System Alerts and Notifications
-- Creates tables for the Alert Agent and Notification Service

-- ============================================================================
-- System Alerts Table
-- ============================================================================
-- Stores alerts generated by the Alert Agent monitoring system metrics

CREATE TABLE IF NOT EXISTS system_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type VARCHAR(50) NOT NULL, -- 'accuracy_drop', 'volume_spike', 'error_rate', 'pattern_failure', etc.
  severity VARCHAR(20) NOT NULL, -- 'critical', 'warning', 'info'
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  metrics JSONB DEFAULT '{}', -- Metric values that triggered the alert
  threshold DECIMAL(10,4) NOT NULL, -- The threshold that was exceeded
  actual_value DECIMAL(10,4) NOT NULL, -- The actual value that triggered alert
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  acknowledged BOOLEAN DEFAULT false,
  acknowledged_by UUID REFERENCES users(id) ON DELETE SET NULL,
  acknowledged_at TIMESTAMP WITH TIME ZONE,
  tenant_id UUID REFERENCES companies(id) ON DELETE CASCADE,
  metadata JSONB DEFAULT '{}', -- Additional context (recommended actions, etc.)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for system_alerts
CREATE INDEX idx_system_alerts_type ON system_alerts(type);
CREATE INDEX idx_system_alerts_severity ON system_alerts(severity);
CREATE INDEX idx_system_alerts_acknowledged ON system_alerts(acknowledged);
CREATE INDEX idx_system_alerts_timestamp ON system_alerts(timestamp DESC);
CREATE INDEX idx_system_alerts_tenant_id ON system_alerts(tenant_id);
CREATE INDEX idx_system_alerts_type_timestamp ON system_alerts(type, timestamp DESC);
CREATE INDEX idx_system_alerts_unacknowledged ON system_alerts(acknowledged) WHERE acknowledged = false;

-- ============================================================================
-- Notifications Table
-- ============================================================================
-- Stores all notifications (in-app, email, slack, webhook)

CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel VARCHAR(20) NOT NULL, -- 'in_app', 'email', 'slack', 'webhook'
  priority VARCHAR(20) NOT NULL DEFAULT 'normal', -- 'low', 'normal', 'high', 'urgent'
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  data JSONB DEFAULT '{}', -- Additional payload data
  status VARCHAR(20) NOT NULL DEFAULT 'pending', -- 'pending', 'sent', 'failed', 'read'
  sent_at TIMESTAMP WITH TIME ZONE,
  read_at TIMESTAMP WITH TIME ZONE,
  tenant_id UUID REFERENCES companies(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  error TEXT -- Error message if failed
);

-- Indexes for notifications
CREATE INDEX idx_notifications_channel ON notifications(channel);
CREATE INDEX idx_notifications_priority ON notifications(priority);
CREATE INDEX idx_notifications_status ON notifications(status);
CREATE INDEX idx_notifications_tenant_id ON notifications(tenant_id);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX idx_notifications_unread ON notifications(user_id, read_at) WHERE read_at IS NULL;
CREATE INDEX idx_notifications_user_unread ON notifications(user_id, created_at DESC) WHERE read_at IS NULL;

-- ============================================================================
-- Alert Thresholds Configuration Table
-- ============================================================================
-- Stores configurable alert thresholds per tenant

CREATE TABLE IF NOT EXISTS alert_thresholds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID REFERENCES companies(id) ON DELETE CASCADE,
  threshold_type VARCHAR(50) NOT NULL, -- 'accuracy_drop', 'volume_spike', etc.
  threshold_value DECIMAL(10,4) NOT NULL,
  cooldown_minutes INTEGER DEFAULT 60,
  channels TEXT[] DEFAULT ARRAY['in_app'], -- Notification channels
  is_enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id, threshold_type)
);

-- Index for alert_thresholds
CREATE INDEX idx_alert_thresholds_tenant_id ON alert_thresholds(tenant_id);
CREATE INDEX idx_alert_thresholds_enabled ON alert_thresholds(is_enabled);

-- ============================================================================
-- Comments
-- ============================================================================

COMMENT ON TABLE system_alerts IS 'Stores system-wide alerts generated by the Alert Agent';
COMMENT ON TABLE notifications IS 'Multi-channel notification storage for in-app, email, slack, and webhook notifications';
COMMENT ON TABLE alert_thresholds IS 'Configurable alert thresholds per tenant';

COMMENT ON COLUMN system_alerts.type IS 'Type of alert: accuracy_drop, volume_spike, error_rate, pattern_failure, confidence_drop, processing_slowdown, feedback_surge, system_health';
COMMENT ON COLUMN system_alerts.severity IS 'Alert severity: critical, warning, info';
COMMENT ON COLUMN system_alerts.metrics IS 'JSON object containing metric values that triggered the alert';
COMMENT ON COLUMN system_alerts.metadata IS 'Additional context including recommended actions';

COMMENT ON COLUMN notifications.channel IS 'Notification channel: in_app, email, slack, webhook';
COMMENT ON COLUMN notifications.priority IS 'Notification priority: low, normal, high, urgent';
COMMENT ON COLUMN notifications.status IS 'Delivery status: pending, sent, failed, read';
COMMENT ON COLUMN notifications.data IS 'Additional payload data for the notification';

-- ============================================================================
-- Trigger for updated_at
-- ============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Only create triggers if they don't exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_system_alerts_updated_at') THEN
    CREATE TRIGGER update_system_alerts_updated_at
      BEFORE UPDATE ON system_alerts
      FOR EACH ROW
      EXECUTE FUNCTION update_updated_at_column();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_alert_thresholds_updated_at') THEN
    CREATE TRIGGER update_alert_thresholds_updated_at
      BEFORE UPDATE ON alert_thresholds
      FOR EACH ROW
      EXECUTE FUNCTION update_updated_at_column();
  END IF;
END;
$$;

-- ============================================================================
-- Default Alert Thresholds (Global)
-- ============================================================================

INSERT INTO alert_thresholds (tenant_id, threshold_type, threshold_value, cooldown_minutes, channels, is_enabled)
VALUES
  (NULL, 'accuracy_drop', 0.15, 60, ARRAY['in_app'], true),
  (NULL, 'volume_spike', 3.0, 60, ARRAY['in_app'], true),
  (NULL, 'error_rate', 0.30, 60, ARRAY['in_app'], true),
  (NULL, 'confidence_drop', 0.20, 60, ARRAY['in_app'], true),
  (NULL, 'processing_slowdown', 2.0, 60, ARRAY['in_app'], true),
  (NULL, 'feedback_surge', 5.0, 60, ARRAY['in_app'], true)
ON CONFLICT DO NOTHING;
